Enhance install_image to determine architecture and version from URL,…
arista-eosplus/ztpserver pull request #405
Opened 2024-04-18 18:37 UTC by Trailingslashes

Images labelled with 32 or 64 should be copied on /mnt/flash with the correct name.

```
drwxrwx---+  2 root      eosadmin      16384 Mar 16  2022 lost+found
drwxrwxr-x+  2 root      eosadmin       4096 Mar 16  2022 Fossil
drwxrwxr-x+  2 root      eosadmin       4096 Mar 16  2022 fastpkttx.backup
drwxrwxrwx+  2 root      eosadmin       4096 Mar 16  2022 .checkpoints
-rw-rw-rw-+  1 root      eosadmin          0 Mar 16  2022 .assetTags
drwxrwxr-x+  3 root      eosadmin       4096 Mar 16  2022 schedule
-rw-rw-r--+  1 106904808 eosadmin 1117379109 Jan  5 10:22 EOS-4.27.11M.swi
drwxrwxr-x+  2 106904808 eosadmin       4096 Jan  5 11:21 .managed-config
-rwxrwxrwx+  1 root      eosadmin       2473 Apr 18 14:26 startup-config
-rwxrwxrwx+  1 root      eosadmin 1254919771 Apr 18 14:26 EOS32-4.29.7M.swi
drwxrwx---+  2 root      eosadmin       4096 Apr 18 14:26 .extensions
-rw-rw-r--+  1 root      eosadmin         29 Apr 18 14:26 boot-config
-r--r-x---+  1 root      eosadmin 1254919771 Apr 18 14:28 .boot-image.swi
drwxr-xr-x   1 root      root            140 Apr 18 14:28 ..
drwxrwxr-x+  3 root      eosadmin       4096 Apr 18 14:28 aboot
drwxrwxr-x+  2 root      eosadmin       4096 Apr 18 14:28 tpm-data
drwxrwx---+ 13 root      eosadmin       4096 Apr 18 14:28 .
-rw-rw-r--+  1 root      eosadmin       1278 Apr 18 14:28 SsuRestoreLegacy.log
-rw-rw-r--+  1 root      eosadmin       1278 Apr 18 14:28 SsuRestore.log
-rw-rw-r--+  1 root      eosadmin       2079 Apr 18 14:28 AsuFastPktTransmit.log
-rw-rw-r--+  1 root      eosadmin          0 Apr 18 14:29 zerotouch-config
drwxrwx---+  3 root      eosadmin       4096 Apr 18 14:29 debug
drwxrwxr-x+  3 root      eosadmin       4096 Apr 18 14:30 persist
```

show version:
```
Hardware version: 11.20
Serial number: JPE22042879
Hardware MAC address: c4ca.2b24.2f41
System MAC address: c4ca.2b24.2f41

Software image version: 4.29.7M
Architecture: i686
Internal build version: 4.29.7M-35658221.4297M
Internal build ID: b9978b0a-8b54-4195-9c83-99f4277ac709
Image format version: 3.0
Image optimization: Default
```

```
---
actions:
  -
    action: install_image
    always_execute: true
    attributes:
      url: files/images/EOS32-4.29.7M.swi
      version: 4.29.7M
    name: "Install 4.29.7M"
```

see #404

2024-04-18 22:08 UTC, siguroot commented
Wouldn't it be better if the filenames were aligned with what is provided by arista.  I personally think the better approach is to just parse the filename out of the provided url attribute.  Thoughts?  

![image](https://github.com/arista-eosplus/ztpserver/assets/133690336/dfd67809-4c75-4191-b0c9-d102a039ff56)

2024-04-19 16:51 UTC, siguroot commented
You'll have to excuse my lack of git experience, I'm still learning.  Anyway, why not just do something as simple as this?:

[install_image](https://github.com/siguroot/ztpserver/blob/image_filename/actions/install_image)

2024-04-19 20:23 UTC, siguroot requested changes
I personally think it makes more sense to just pass the filename given in the url attribute variable to the destination filename:

```
image = url.split("/")[-1]
```

Like so, [install_image](https://github.com/siguroot/ztpserver/commit/904a3dc93f5ad2fec59e99d29e6c8e450fd840ad)

2024-04-22 13:35 UTC, Trailingslashes commented
I guess my thinking was to read the url in the definition and reconstruct the name of the file based on that. When I read a file on /mnt/flash, I want to know if it's a 32 or 64 bit file right away. I don't want to rely on the md5sum. But yes, you're right, following Arista's standard - if there is no 64bit in the name, we can assume it's 32 bit right away.

2024-04-22 15:02 UTC, Trailingslashes commented
You're more than welcome to create your own pull request.

2024-05-02 09:34 UTC, dlobato commented
Closing as #406 implements similar functionality

2024-05-02 09:34 UTC, closed without merging